### PR TITLE
skip tests requiring webfakes

### PR DESCRIPTION
**Pull request by MichaelChirico**

### CODE REVIEW

**Comment by hadley** [comment]
Would you mind explaining the root problem?

**Comment by MichaelChirico** [comment]
pretty simple: webfakes is unavailable 🙂

**Comment by hadley** [comment]
And what's the root cause of that? 😆

**Comment by MichaelChirico** [comment]
two main things:

 1. there's manual overhead for us to bring in incremental packages -- https://opensource.google/documentation/reference/thirdparty. so unless we need Suggests functionality, we usually don't import those deps (e.g. just to pass a small # of tests)
 2. our test infra blocks web calls. i'm not sure webfakes even can work (speculative -- haven't looked into webfakes much)

we have already applied the patch to our fork, but filed here as well thinking it's more generally useful. but do feel free to close.

**Comment by hadley** [comment]
Thanks! Just wanted to understand the root context; I'll likely merge when I'm next working on testthat.

**Pull request closed without merging**
